/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kyen_lhm_ffmpeglib_FFMPEGLib */

#ifndef _Included_kyen_lhm_ffmpeglib_FFMPEGLib
#define _Included_kyen_lhm_ffmpeglib_FFMPEGLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kyen_lhm_ffmpeglib_FFMPEGLib
 * Method:    Test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_kyen_lhm_ffmpeglib_FFMPEGLib_Test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
